ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('main.urls')),
    path('catalog/', include('goods.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('carts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path 
from . import views 


urlpatterns = [
    path('', views.main_page, name='home'),
    path('about/', views.about, name='about')
]

users/urls.py
from django.urls import path 
from . import views 


urlpatterns = [
    path('registration/', views.registration, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.update_profile, name='update_profile'),
    path('cart/', views.user_cart, name='cart'),
]

goods/models.py
from django.db import models
from django.utils.text import slugify


class Gender(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name 


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    class Meta:
        ordering = ('id',)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='sneakers/')
    price = models.FloatField(default=0.00)
    discount = models.IntegerField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)


    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price


    def article(self):
        return f'{self.id:05}'


    def __str__(self):
        return self.name
    

class ProductColor(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

class ProductSize(models.Model):
    size = models.DecimalField(default=00.0, max_digits=3, decimal_places=1)
    remains = models.PositiveIntegerField()
    

class ProductItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.DecimalField(default=00.0, max_digits=3, decimal_places=1)
    remains = models.PositiveIntegerField()

    
    def __str__(self):
        return f'{self.product.name} | {self.size} | {self.remains}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True)

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = get_user_model()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        )

    image = forms.ImageField(required=False)
    

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required


from .forms import UserLoginForm, UserRegistrationForm, ProfileForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                # messages.success(request, f'{username} successfully log in.')

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('home'))
    else:
        form = UserLoginForm()
        
    return render(request, 'users/login.html', {'form': form})


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('home'))
    else:
        form = UserRegistrationForm()

    return render(request, 'users/registration.html', {'form': form})


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('home'))


@login_required
def profile(request):
    return render(request, 'users/profile.html')


@login_required
def update_profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile'))
    else:
        form = UserRegistrationForm(instance=request.user)

    return render(request, 'users/update_profile.html', {'form': form})


def user_cart(request):
    return render(request, 'users/cart_page.html')

users/templates/users/cart_page.html
{% extends 'base.html' %}
{% load static %} 
{% load cart_tag %}


{% block css %} 
<link rel="stylesheet" href="{% static 'css/cart_style.css' %}">
{% endblock %}


{% block content %}
{% get_user_carts request as carts %}

<section class="main_section">
    <div class="container">
        <h2 class="main__title">Your cart (<span id="cart-items">{{ carts.total_qty }}</span> items)</h2>
        <div class="cart__label__wrap">
            <p class="cart__label cart__label_main">Item</p>
            <p class="cart__label">Size</p>
            <p class="cart__label">Price</p>
            <p class="cart__label">Quantity</p>
            <p class="cart__label">Total</p>
            <p class="cart__label"></p>
        </div>
        {% for cart in carts %}
        <div class="cart__item__wrap" data-cart-id="{{ cart.id }}">
            <div class="cart__item__product__wrap">
                <img class="cart__item__product__img" src="{{ cart.product_item.product.image.url }}" alt="">
                <p class="cart__item__product__name">{{ cart.product_item.product.name }}</p>
            </div>
            <p class="cart__item__size cart__item">{{ cart.product_item.size }}</p>
            <p class="cart__item__price cart__item">Rs/- {{ cart.product_item.product.sell_price }}</p>
            <div class="cart__item__qty__wrap cart__item">
                <button type="button" class="cart__item__qty__btn increment" data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart_change" %}">+</button>
                {% csrf_token %}
                <p class="cart__item__qty cart-item-qty">{{ cart.quantity }}</p>
                <button type="button" class="cart__item__qty__btn decrement" data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart_change" %}">-</button>
                {% csrf_token %}
            </div>
            <p class="cart__item__total-price cart__item">Rs/- {{ cart.product_price }}</p>
            <p class="cart__item__delete-link"><a href="{% url 'cart_remove' %}" data-cart-id="{{ cart.id }}" class="material-icons ajax-remove">clear</a></p>
            {% csrf_token %}
        </div>
        {% endfor %}
        <div class="cart__result__wrap">
            {% comment %} <div class="cart__result__item">
                <p class="cart__result__item__label">Subtotal:</p>
                <p class="cart__result__item__total">$1926</p>
            </div> {% endcomment %}
            <div class="cart__result__item">
                <p class="cart__result__item__label">Grand total:</p>
                <p class="cart__result__item__total cart__result__item__total_grand">Rs/- {{ carts.total_price }}</p>
            </div>
        </div>
        <a href="#" class="cart__result__checkout">Check Out</a>

    </div>
</section>

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/users_style.css' %}">
{% endblock %}


{% block content %}

<section class="main_section">
    <div class="container container_users">
        <div class="form__wrap">
            <h2 class="main__title">Login</h2>
            <form method="post" class="users__form">
                {% csrf_token %}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                
                <p class="error-text">{% if form.non_field_errors %}{{ form.non_field_errors.as_text }}{% endif %}</p>
                
                <div class="form__item">
                    <label for="id_name" class="form__label">Username*</label>
                    <input type="text" name="username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" class="form__field" id="id_name" required>
                </div>
                <div class="form__item">
                    <label for="id_password" class="form__label">Password*</label>
                    <input type="password" name="password" class="form__field" id="id_password" required> 
                </div>

                <p>* - required field</p>
                <button class="form__button" type="submit">Submit</button> 
            </form>
            <div class="auth__links__wrap">
                <a href="#" class="auth__link">Forgot the password?</a>
                <span> | </span>
                <a href="{% url 'register' %}" class="auth__link">Create profile</a>
            </div> 
            <div class="auth__another__wrap">
                <p class="auth__another__title">Other authorization methods:</p>
                <div class="auth__another__links__wrap">
                    <a href="#" class="auth__another__link"><img src="{% static 'img/icons/google.svg' %}" alt="#" class="auth__another__link__img"> Google</a>
                    <a href="#" class="auth__another__link"><img src="{% static 'img/icons/facebook.svg' %}" alt="#" class="auth__another__link__img"> Facebook</a>
                    <a href="#" class="auth__another__link"><img src="{% static 'img/icons/github.svg' %}" alt="#" class="auth__another__link__img"> GitHub</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/users_style.css' %}">
{% endblock %}


{% block content %}

<section class="main_section">
    <div class="container container_profile">
        <h2 class="main__title">Your profile</h2>
        <div class="profile__info__wrap">
            {% if user.image %}
            <img class="profile__img" src="{{ user.image.url }}" alt="user_image">
            {% else %}
            <img class="profile__img" src="{% static 'img/default_image.png' %}" alt="default_image">
            {% endif %}
            <div class="profile__info">
                <div class="profile__name__update__wrap">
                    <p class="profile__name">{{ user.first_name }} {{ user.last_name }}</p>
                    <a href="{% url 'update_profile' %}" class="profile__update__link">Update profile</a>
                </div>
                <p class="profile__username">username: {{ user.username }}</p>
                <p class="profile__email">email: {{ user.email }}</p>
                <div class="profile__analytics__wrap">
                    <div class="profile__analytics__item">
                        <p class="profile__analytics__detail">Purchased sneakers:</p>
                        <p class="profile__analytics__detail-total">4</p>
                    </div>
                    <div class="profile__analytics__item">
                        <p class="profile__analytics__detail">Amount of purchases:</p>
                        <p class="profile__analytics__detail-total">$1274</p>
                    </div>
                </div>
            </div>
        </div>
        <h2 class="profile__orders__title">Your orders:</h2>
        <div class="profile__orders__wrap">
            <div class="profile__order__item">
                <div class="profile__order__info__wrap">
                    <p class="profile__order__info">Order № 256 - 03/27/2024 16:51</p>
                    <p>Status: <span class="profile__order__status">in processed</span></p>
                </div>
                <a href="#" class="profile__order__detail__link">Order details</a>
            </div>
            <div class="profile__order__item">
                <div class="profile__order__info__wrap">
                    <p class="profile__order__info">Order № 241 - 03/15/2024 08:21</p>
                    <p>Status: <span class="profile__order__status">completed</span></p>
                </div>
                <a href="#" class="profile__order__detail__link">Order details</a>
            </div>
            <div class="profile__order__item">
                <div class="profile__order__info__wrap">
                    <p class="profile__order__info">Order № 213 - 02/19/2024 13:01</p>
                    <p>Status: <span class="profile__order__status">completed</span></p>
                </div>
                <a href="#" class="profile__order__detail__link">Order details</a>
            </div>

        </div>
        <a href="#" class="profile__order__history">Show the order history</a>
    </div>
</section>

{% endblock %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/users_style.css' %}">
{% endblock %}


{% block content %}

<section class="main_section">
    <div class="container container_users">
        <div class="form__wrap">
            <h2 class="main__title">Register</h2>
            <form method="post" class="users__form">
                {% csrf_token %}
                <div class="form__item">
                    <label for="id_name" class="form__label">Name*</label>
                    <input type="text" placeholder="Ivan" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" name="first_name" class="form__field" id="id_name" required>
                    {% if form.first_name.errors %}
                    <p class="error-text">{{ form.first_name.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">
                    <label for="id_surname" class="form__label">Surname*</label>
                    <input type="text" placeholder="Ivanov" value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"  name="last_name" class="form__field" id="id_surname" required> 
                    {% if form.last_name.errors %}
                    <p class="error-text">{{ form.last_name.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">
                    <label for="id_username" class="form__label">Username*</label>   
                    <input type="text" placeholder="IvanIvanIvan" value="{% if form.username.value %}{{ form.username.value }}{% endif %}"  name="username" class="form__field" id="id_username" required> 
                    {% if form.username.errors %}
                    <p class="error-text">{{ form.username.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">
                    <label for="id_email" class="form__label">Email*</label>  
                    <input type="email" placeholder="ivan@ivan.com" value="{% if form.email.value %}{{ form.email.value }}{% endif %}"  name="email" class="form__field" id="id_email" required>  
                    {% if form.email.errors %}
                    <p class="error-text">{{ form.email.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">  
                    <label for="id_password" class="form__label">Password*</label>
                    <input type="password" placeholder="Your password" name="password1" class="form__field" id="id_password" required> 
                    {% if form.password1.errors %}
                    <p class="error-text">{{ form.password1.errors.as_text }}</p>
                    {% endif %}
                </div> 

                <div class="form__item">
                    <label for="id_repassword" class="form__label">Repassword*</label>  
                    <input type="password" placeholder="Repeat password" name="password2" class="form__field" id="id_repassword" required> 
                    {% if form.password2.errors %}
                    <p class="error-text">{{ form.password2.errors.as_text }}</p>
                    {% endif %} 
                </div>

                <p>* - required field</p>
                <button class="form__button" type="submit">Submit</button>  
            </form>
        </div>
    </div>
</section>

{% endblock %}

users/templates/users/update_profile.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/users_style.css' %}">
{% endblock %}


{% block content %}

<section class="main_section">
    <div class="container container_users">
        <div class="form__wrap">
            <h2 class="main__title">Edit profile</h2>
            <form method="post" class="users__form" enctype="multipart/form-data">
                {% csrf_token %}
                {% if user.image %}
                <div class="form__image__wrap">
                    <img class="form__image" src="{{ user.image.url }}" alt="user_image">
                </div>
                {% else %}
                <div class="form__image__wrap">
                    <img class="form__image" src="{% static 'img/default_image.png' %}" alt="default_image">
                </div>
                {% endif %}
                
                <div class="form__item">
                    <label for="id_image" class="form__label">Image</label>
                    <input type="file" name="image" class="form__field" id="id_image">
                    {% if form.image.errors %}
                    <p class="error-text">{{ form.image.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">
                    <label for="id_name" class="form__label">Name</label>
                    <input type="text" value="{{ form.first_name.value }}" name="first_name" class="form__field" id="id_name">
                    {% if form.first_name.errors %}
                    <p class="error-text">{{ form.first_name.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">
                    <label for="id_surname" class="form__label">Surname</label>
                    <input type="text" value="{{ form.last_name.value }}" name="last_name" class="form__field" id="id_surname"> 
                    {% if form.last_name.errors %}
                    <p class="error-text">{{ form.last_name.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">
                    <label for="id_username" class="form__label">Username</label>   
                    <input type="text" value="{{ form.username.value }}"  name="username" class="form__field" id="id_username"> 
                    {% if form.username.errors %}
                    <p class="error-text">{{ form.username.errors.as_text }}</p>
                    {% endif %}
                </div>

                <div class="form__item">
                    <label for="id_email" class="form__label">Email</label>  
                    <input type="email" value="{{ form.email.value }}" name="email" class="form__field" id="id_email">  
                    {% if form.email.errors %}
                    <p class="error-text">{{ form.email.errors.as_text }}</p>
                    {% endif %}
                </div>

                <button class="form__button" type="submit">Update profile</button>  
            </form>
        </div>
    </div>
</section>

{% endblock %}